apiVersion: v1
kind: Secret
metadata:
  name: n8n-api-key
  namespace: middleware
type: Opaque
data:
  api-key: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnpkV0lpT2lJeVlUSm1Nemt5WXkwek1HWmpMVFF6TjJNdE9UYzVNeTA1TkRBNU1EQmpPR05pWXpNaUxDSnBjM01pT2lKdU9HNGlMQ0poZFdRaU9pSndkV0pzYVdNdFlYQnBJaXdpYW5ScElqb2lNekZsTURNNU56TXRNbVV6TmkwME9XTTBMVGhtWWpVdE5qY3dPV1k1Tmpnek1qSmtJaXdpYVdGMElqb3hOemMxT0RBek16RXpMQ0psZUhBaU9qRTNOemd6TmpRd01EQjkuS2gxT2NaRlJlLTBfRmIySElHb0xqLXUza0NYWkJBTzVxTjVNdWNCZlRuRQ==
