apiVersion: v1
kind: Secret
metadata:
  name: n8n-api-key
  namespace: middleware
type: Opaque
data:
  api-key: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnpkV0lpT2lJeVlUSm1Nemt5WXkwek1HWmpMVFF6TjJNdE9UYzVNeTA1TkRBNU1EQmpPR05pWXpNaUxDSnBjM01pT2lKdU9HNGlMQ0poZFdRaU9pSndkV0pzYVdNdFlYQnBJaXdpYW5ScElqb2lNRFJtTldGbE1HSXRPREl5WmkwME5qaGhMV0V5T0dFdE5UVTNOekkyT0RJME1UUmhJaXdpYVdGMElqb3hOemMxT0RBME1UYzFmUS5uV0RuNEYwTnBtUUtMcXNqTE05dnhlMVdBaVpMNHBwMTBfaXBNeGlLcktn
