apiVersion: v1
kind: Secret
metadata:
  name: n8n-imap-credential
  namespace: middleware
type: Opaque
stringData:
  user: "minh.hoang@seashorehotel.com.vn"
  password: "CwawSMLwzPilAp6V"
  host: "imap.larksuite.com"
  port: "993"
