apiVersion: v1
kind: Secret
metadata:
  name: n8n-openai-credential
  namespace: middleware
type: Opaque
stringData:
  apiKey: "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"
