apiVersion: v1
kind: Secret
metadata:
  name: n8n-postgres-credential
  namespace: middleware
type: Opaque
stringData:
  Host: postgres-service.database.svc.cluster.local
  Database: email_ai
  User: admin
  Password: "123456"
  Port: "5432"
