apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "email_ai"
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "123456"

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: database
spec:
  type: NodePort          # <--- ĐỔI TỪ ClusterIP SANG NodePort
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30432     # <--- THÊM DÒNG NÀY, chọn cổng từ 30000-32767
