apiVersion: apps/v1
kind: Deployment
metadata:
  name: libreoffice-server
  namespace: middleware
  labels:
    app: libreoffice-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: libreoffice-server
  template:
    metadata:
      labels:
        app: libreoffice-server
    spec:
      containers:
      - name: libreoffice
        image: ghcr.io/unoconv/unoserver-docker:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 2002
          name: unoserver
          protocol: TCP
        env:
        - name: UNOSERVER_HOST
          value: "0.0.0.0"
        - name: UNOSERVER_PORT
          value: "2002"
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests:
            memory: "512Mi"
            cpu: "250m"
        # ĐÃ XÓA LIVENESS VÀ READINESS PROBE
---
apiVersion: v1
kind: Service
metadata:
  name: libreoffice-server
  namespace: middleware
  labels:
    app: libreoffice-server
spec:
  type: ClusterIP
  selector:
    app: libreoffice-server
  ports:
  - name: unoserver
    port: 33101
    targetPort: 2002
    protocol: TCP
