apiVersion: apps/v1
kind: Deployment
metadata:
  name: libreoffice-server
  namespace: middleware
  labels:
    app: libreoffice-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: libreoffice-server
  template:
    metadata:
      labels:
        app: libreoffice-server
    spec:
      containers:
      - name: libreoffice
        image: leplusorg/libreoffice-rest:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: REST_API_PORT
          value: "8080"
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests:
            memory: "512Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: libreoffice-server
  namespace: middleware
  labels:
    app: libreoffice-server
spec:
  type: ClusterIP
  selector:
    app: libreoffice-server
  ports:
  - name: http
    port: 33101
    targetPort: 8080
    protocol: TCP
